pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        script:
          - git clone --bare git@github.com:koopa31/napari_svetlana.git
          - cd napari_svetlana.git
          - git push --mirror git@github.com:koopa31/napari_svetlana.git