labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - 3D Image # Data Shape
  - 2D Image
  - Multichannel Image
  - Object classification # Processing step
  - Deep-learning-based classification # Processing step
  - Outliers Removal